@startuml
skinparam shadowing false
skinparam DefaultFontName "Segoe UI"
skinparam TitleFontSize 18

title Pipeline de Tradução

|Leitor|
start
:Fornecer Página Original;

|FTM\n(Sistema/Orquestrador)|
:Inicializar BubbleZones;

|Detector\n(Motor ML)|
:Detectar Bounding Boxes;
'note right
'  **Popula BubbleZone:**
'  * id, x, y, w, h
'  * detection_method
'  * detection_time_s
'end note

|FTM\n(Sistema/Orquestrador)|
:Recortar Imagens;
'note right: popula **crop**

|Extrator\n(Motor ML)|
:Extrair Texto;
'note right
'  **Popula:**
'  * jp_text
'  * extraction_symbols
'  * extraction_time_s
'end note

|FTM\n(Sistema/Orquestrador)|
:Enviar Texto;


|Tradutor\n(Motor ML)|
:Traduzir Texto;
'note right
'  **Popula:**
'  * translated_text
'  * translation_symbols
'  * translating_time_s
'end note

|FTM\n(Sistema/Orquestrador)|
:Sobrescrever Texto;
'note right
'  **Popula:**
'  * typesetting_characters
'  * typesetting_time_s
'end note

|Leitor|
:Visualizar Página Traduzida;
stop
@enduml