@startuml
left to right direction

class FTM

package "profiler" as profiler {
    class ResourceMonitor
    class MonitorContext <<ContextVar>>
    class step <<decorator>>
}
package "dto" as dto {
    class BubbleZone <<TypeDict>>
}
package "steps" as steps {
    package "detection" {
        abstract class EngineOCR
        class EngineOCRFactory
        class YOLOTextDetector extends EngineOCR
    }
    package "extraction" {
        abstract class TextExtractor
        class MangaOCRExtractor extends TextExtractor
    }
    package "translation" {
        abstract class Translator
        class OllamaTranslator extends Translator
    }
    package "typesetting" {
        class BubbleTypesetter
    }
}

' Relações de Orquestração
FTM o-- ResourceMonitor
FTM .. MonitorContext
FTM .. BubbleZone
' Relações de Profiling
step .. MonitorContext
step .. ResourceMonitor
' Relações de Execução (Dependency Injection/Usage)
FTM .. EngineOCRFactory
FTM .. TextExtractor
FTM .. Translator
FTM .. BubbleTypesetter
EngineOCRFactory .. YOLOTextDetector

' Layout
FTM -[hidden]right- dto
dto -[hidden]right- profiler
dto -[hidden]down- steps

@enduml